stages:
  - build

build:
  services:
    - name: docker:dind
      command: [ "--insecure-registry=d3s-server.d3s:5050" ]
  image: docker:latest
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$(echo $CI_COMMIT_BRANCH | tr / -)
    - "[[ -z $NO_CACHE ]] && (docker pull $IMAGE --quiet || (docker pull $CI_REGISTRY_IMAGE:cache --quiet && docker tag $CI_REGISTRY_IMAGE:cache $IMAGE) || true)"
    - docker build -f docker/Dockerfile --tag $IMAGE --cache-from $IMAGE --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker tag $IMAGE $CI_REGISTRY_IMAGE:cache
    - docker push $CI_REGISTRY_IMAGE --all-tags --quiet
  when: manual
