"""Initial migration

Revision ID: dd748f0911c9
Revises: 
Create Date: 2024-06-15 13:06:23.300226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd748f0911c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('vector', pgvector.sqlalchemy.Vector(), nullable=True))
    op.create_index(op.f('ix_items_vector'), 'items', ['vector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_vector'), table_name='items')
    op.drop_column('items', 'vector')
    # ### end Alembic commands ###
