version: '3'
name: 'labelizer'
services:
  back:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    command: gunicorn --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:42042 labelizer.core.api.fast_api_app:app
    ports:
      - 42042:42042
    environment:
      ROOT_PATH: /app/data
      DEV_MOD: 1
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: labelizer
      DB_SCHEMA: labelizer
      DB_USER: postgres
      DB_PASSWORD: postgres

    volumes:
      - workspace-data:/app/data

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5452:5432"
    volumes:
      - ./docker/initdb_scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  workspace-data:
  pgdata: