version: '3'
name: 'labelizer'
services:
  back:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    command: gunicorn --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:42042 labelizer.core.api.fast_api_app:app
    ports:
      - 42042:42042
    environment:
      ROOT_PATH: /app/data
    volumes:
      - ./workspace:/app/data

